### ISSUE TITLE
Linux build instructions

### ISSUE THREAD

**Issue by ggerganov** [gallickgunner/Volume-Renderer#1]
I would love to check this project out. Have you been able to run it on Ubuntu?

**Comment by gallickgunner** [comment]
Hello, extremely sorry for the late reply as I am quite busy applying for masters. I appreciate your interest, however I haven't tested it on Linux/Ubuntu. I'll try to check with travis-ci as soon as I get free.

Again, I haven't included a makefile or something of the sort but the project is pretty easy to build if you are using an IDE like CodeBlocks. Just add the path to the `Dear-ImGui` folder in the search directory options so that all the files in it are accessible as is.

**Comment by ggerganov** [comment]
No problem, good luck with the application.

**Comment by ggerganov** [comment]
So I was able to build it on Ubuntu 18.04 with the following command:

```
g++ main.cpp -I Dear-IMGUI/ -I include -I ./glad/include/ ./src/*.cpp -fpermissive Dear-IMGUI/*.cpp ./glad/src/glad.c  -lglfw -ldl
```

Had to download `glad.h` and `glad.c` and install `libglm-dev`.
Works very smooth!
